# Generated by Django 4.1.3 on 2023-01-29 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='food_list',
            fields=[
                ('food_id', models.AutoField(primary_key=True, serialize=False)),
                ('food_title', models.CharField(max_length=50)),
                ('user_post_id', models.IntegerField()),
                ('location', models.CharField(max_length=100)),
                ('packets', models.CharField(max_length=20)),
            ],
        ),
    ]
