# Generated by Django 4.1.3 on 2023-01-29 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post_food', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='food_list',
            name='Rst_name',
            field=models.CharField(default=' ', max_length=50),
            preserve_default=False,
        ),
    ]
