# Generated by Django 4.1.3 on 2023-01-29 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post_food', '0002_food_list_rst_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='food_list',
            name='image',
            field=models.ImageField(default='', upload_to='image'),
            preserve_default=False,
        ),
    ]
