# Generated by Django 4.1.3 on 2023-01-31 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post_food', '0003_food_list_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='food_list',
            name='date',
            field=models.CharField(default=' ', max_length=11),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='food_list',
            name='time',
            field=models.CharField(default='', max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='food_list',
            name='image',
            field=models.ImageField(upload_to='images'),
        ),
    ]
