# Generated by Django 4.1.3 on 2023-02-05 04:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('post_food', '0004_food_list_date_food_list_time_alter_food_list_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order_list',
            fields=[
                ('order_id', models.AutoField(primary_key=True, serialize=False)),
                ('user_id', models.IntegerField()),
                ('status', models.CharField(default='waiting', max_length=15)),
                ('date', models.DateField()),
                ('food_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='post_food.food_list')),
            ],
        ),
    ]
