# Generated by Django 4.1.3 on 2023-02-05 05:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post_food', '0005_order_list'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order_list',
            name='date',
            field=models.DateField(default=datetime.datetime.today),
        ),
    ]
