# Generated by Django 4.1.3 on 2023-02-09 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_users_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='status',
            field=models.IntegerField(default=0),
        ),
    ]
